export type IconNames =
  | 'bars'
  | 'calendar'
  | 'check'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'circle-check'
  | 'circle-minus'
  | 'circle-plus'
  | 'circle-question'
  | 'circle-xmark'
  | 'clock'
  | 'close'
  | 'download'
  | 'ellipsis-h'
  | 'ellipsis-v'
  | 'gear'
  | 'image'
  | 'print'
  | 'search'
  | 'solid-star'
  | 'star'
  | 'thumbs-up'
  | 'trash'
  | 'trash-can';

export type IconSizes = 'regular' | 'large' | 'xlarge';

export type IconVariants =
  | 'primary'
  | 'secondary'
  | 'tertiary'
  | 'destructive'
  | 'action'
  | 'success'
  | 'error'
  | 'accent'
  | 'accent-dark'
  | '';
